export { default as Home } from  '../Pages/Home';
export { default as Earn } from '../Pages/Earn';
export { default as Connect } from '../Pages/Connect';
export { default as Learn } from  '../Pages/Learn';
// import { Wallet } from '../Pages/Wallet';
// import { WalletConnect } from '../Pages/WalletConnect';
// import { WalletDisconnect } from '../Pages/WalletDisconnect';
// import { WalletDisconnectConfirm } from '../Pages/WalletDisconnectConfirm';
export { default as Navbar } from '../Components/Navbar/Navbar';
export { default as Footer } from '../Components/Footer/Footer';
export { default as Hero } from '../Components/Hero/Hero';
export { default as Wearables } from  '../Components/Wearables/Wearables';
export { default as Wearable } from  '../Components/Wearable/Wearable';
export { default as Explorer } from  '../Components/Explorer/Explorer';
export { default as Roadmap } from  '../Components/Roadmap/Roadmap';
export { default as ForYouFavorites } from '../Components/ForYouFavorites/ForYouFavorites';
export { default as EngageCreate } from '../Components/EngageCreate/EngageCreate';
export { default as HowItWorks } from '../Components/HowItWorks/HowItWorks';
export { default as Signup } from '../../src/Pages/Signup/Signup';
export { default as ConnectInteract } from '../Components/ConnectInteract/ConnectInteract';
export { Navigations } from '../utils';
export { default as Spaces } from '../Components/Spaces/Spaces';
export { default as Team } from '../Components/Team/Team';
export { default as SpaceDesign } from '../Components/Space Design/SpaceDesign';
export { default as Faq } from '../Components/Faq/Faq';
export { default as ProfilePics } from '../Assets/Wallpaper_11.jpg';
export { default as BuildIcon } from '../Assets/icon _build.png';
export { default as TestingIcon } from '../Assets/icon_beta_testing.png';
export { default as LaunchIcon } from '../Assets/icon_launch.png';
export { default as wisdomODP } from '../Assets/wisdomODP.png';
export { default as Showcase }  from './Showcase/Showcase';
export { default as ThumbsUpImg } from '../Assets/Thumbs_up.png';
export { default as DottedLine } from '../Assets/dotted_Line.png';
export { default as companyLogo } from '../Assets/EduXverse-03.png';
export { default as HeroImg } from '../Assets/Hero Image Design.png';
export { default as GeorgeDP } from '../Assets/GeorgeDP.png';
export { default as RevivalDP } from '../Assets/RevivalDPEdit.jpg';
export { default as IsraelOshozokhaDP } from '../Assets/IsraelOshozokhaDPEdit.jpg';
export { default as AyoSamuelDP } from '../Assets/AyoSamuelDP.png';
export { default as DivineDP } from '../Assets/DivineDPEdit.jpg';
export { default as F0FDP } from '../Assets/Wallpaper_11.jpg';
export { default as SuiLogo } from '../Assets/Sui_Logo.png';
export { default as BenedicatOchaiDP } from '../Assets/BenedicatOchaiDP.jpg';
export { default as MichaelObeDP } from '../Assets/MichaelObeDP.jpg';
export { default as AvatarImg } from '../Assets/Avatar_Img.jpg';
export { default as FootIcon } from '../Assets/FootIcon.png';
export { default as CoinIcon } from '../Assets/CoinIcon.png';
export { default as AccProfilePics } from '../Assets/accProfilePics.png';
export { default as EdxVest } from '../Assets/EdxVest.png';
export { default as EdxHeadset } from '../Assets/EdxHeadset.png';
export { default as BlobImg } from '../Assets/BlobImg.png';
export { default as BlockchainQuizImg } from '../Assets/BlockchainQuizImg.png'
export { default as BookMarkFolder } from '../Assets/BookMarkFolder.png'
export { default as Quiz } from '../Pages/Quiz/Quiz';
export { default as UserPanel } from '../Pages/UserPanel/UserPanel';